/* eslint-disable no-console */
const fs = require('fs');
const path = require('path');

const projectRoot = path.resolve(__dirname, '..');
const videosDir = path.join(projectRoot, 'assets', 'videos', 'workout-videos');
const outputFile = path.join(projectRoot, 'src', 'utils', 'workoutVideoManifest.ts');

const normalize = (name) =>
  name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .replace(/_+/g, '_');

const main = () => {
  if (!fs.existsSync(videosDir)) {
    console.error(`Workout videos directory not found at ${videosDir}`);
    process.exit(1);
  }

  const files = fs
    .readdirSync(videosDir)
    .filter((file) => file.toLowerCase().endsWith('.mp4'))
    .sort();

  if (!files.length) {
    console.error('No workout videos found to generate manifest.');
    process.exit(1);
  }

  const header = [
    '// Auto-generated by scripts/generateWorkoutVideoManifest.js',
    '// Do not edit manually. Run the script again after adding/removing videos.',
    '',
    'export const workoutVideoFileNames: Record<string, string> = {',
  ];

  const fileNameEntries = files.map((file) => {
    const slug = normalize(path.basename(file, path.extname(file)));
    return `  '${slug}': '${file}',`;
  });

  const footer = [
    '};',
    '',
    'export const workoutVideoSlugs = Object.keys(workoutVideoFileNames);',
    '',
    'export const normalizeWorkoutVideoKey = (name?: string | null): string | null => {',
    '  if (!name) return null;',
    "  return name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '').replace(/_+/g, '_');",
    '};',
    '',
    'const findFuzzyKey = (slug: string): string | undefined => {',
    '  const parts = slug.split("_").filter(Boolean);',
    '  return workoutVideoSlugs.find((key) => {',
    '    if (key === slug || key.includes(slug) || slug.includes(key)) {',
    '      return true;',
    '    }',
    '    const keyParts = key.split("_").filter(Boolean);',
    '    return parts.every((part) => keyParts.includes(part));',
    '  });',
    '};',
    '',
    'export const resolveWorkoutVideoFileName = (name?: string | null): string | null => {',
    '  const slug = normalizeWorkoutVideoKey(name);',
    '  if (!slug) return null;',
    '  const key = workoutVideoFileNames[slug] ? slug : findFuzzyKey(slug);',
    '  return key ? workoutVideoFileNames[key] : null;',
    '};',
    '',
  ];

  fs.writeFileSync(outputFile, [...header, ...fileNameEntries, ...footer].join('\n'));
  console.log(`✅ Generated manifest with ${files.length} videos at ${outputFile}`);
};

main();
